context:
  version: 0.2.10

package:
  name: scalariform
  version: ${{ version }}

source:
  url: https://github.com/scala-ide/scalariform/archive/${{ version }}.tar.gz
  sha256: 7ffbb50cb3ee9161abcdaab2f15727d3c3dbe6a2c185463ab8ef6432f92e7e91

build:
  number: 0
  noarch: generic

requirements:
  build:
    - findutils
    - maven
    - sbt
    - openjdk >=11,<12
  run:
    - openjdk

tests:
  - script:
      - scalariform --help

about:
  license: MIT
  license_file: LICENCE
  summary: Scala source code formatter
  homepage: https://github.com/scala-ide/scalariform
  repository: https://github.com/scala-ide/scalariform

extra:
  recipe-maintainers:
    - danielnachun
